open Test_utils
open String_ext
open Muaddebt

let get_todos (filename : string) : Todo.t list = [
     {
       urgency  = 0;
       msg      = "Test TODO";
       marker   = Marker.Todo;
       location = { file = filename; line = 1; column = 1 };
    };
  ]

let test_no_readme () =
  let file_path = (fun () ->
      let res, _ = open_temp_file () in
      Sys.remove res;
      res
  )
  |> or_fail_with_exn "failed to create temp file"
  in

  Readme_io.update_readme ~file_path (get_todos file_path)
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme = Printf.sprintf {|
## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|} file_path |> String.trim_left in

  read_whole_file file_path |> Alcotest.(check visible_string)
    "same content" expected_readme

let test_empty_readme () =
  with_temp_file begin fun ~file_path _oc ->
    Readme_io.update_readme ~file_path (get_todos file_path)
    |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

    let expected_readme = Printf.sprintf {|
## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|} file_path |> String.trim_left
    in
    read_whole_file file_path |> Alcotest.(check visible_string)
      "same content" expected_readme
  end

let test_no_dashboard () =
  let init_content = fun _ -> {|
# Test README.md

Contains a single paragraph. Tech-debt dashboard should be added below
with a an empty line as separation👇.
|} |> String.trim_left
  in
  with_temp_file ~init_content begin fun ~file_path _oc ->
    Readme_io.update_readme ~file_path (get_todos file_path)
    |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

    let expected_readme = Printf.sprintf {|
# Test README.md

Contains a single paragraph. Tech-debt dashboard should be added below
with a an empty line as separation👇.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|} file_path |> String.trim_left
    in
    read_whole_file file_path |> Alcotest.(check visible_string)
      "same content" expected_readme
  end

let test_dashboard_at_top () =
  let init_content = fun (file_path:string) -> Printf.sprintf {|
## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|} file_path |> String.trim_left
  in
  with_temp_file ~init_content begin fun ~file_path _oc ->
    Readme_io.update_readme ~file_path (get_todos file_path)
    |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

    let expected_readme = Printf.sprintf {|
## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|} file_path |> String.trim_left in

    read_whole_file file_path |> Alcotest.(check visible_string)
      "same file_path" expected_readme
  end

let test_dashboard_in_middle () =
  let init_content = fun (file_path:string) -> Printf.sprintf {|
# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|} file_path |> String.trim_left
  in
  with_temp_file ~init_content begin fun ~file_path _oc ->
    Readme_io.update_readme ~file_path (get_todos file_path)
    |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

    let expected_readme = Printf.sprintf {|
# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|} file_path |> String.trim_left in

    read_whole_file file_path |> Alcotest.(check visible_string)
      "same file_path" expected_readme
  end

let test_dashboard_at_end () =
  let init_content = (fun (file_path:string) -> Printf.sprintf {|
# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|} file_path |> String.trim_left)
  in
  with_temp_file ~init_content begin fun ~file_path _oc ->
    Readme_io.update_readme ~file_path (get_todos file_path)
    |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

    let expected_readme = Printf.sprintf {|
# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|} file_path |> String.trim_left in

    read_whole_file file_path |> Alcotest.(check visible_string)
      "same file_path" expected_readme
  end
