open Muaddebt

let filename, suffix = ("README", ".md")

let or_fail_with ~pp_error (msg : string) = function
  | Ok v -> v
  | Error e -> Alcotest.failf "%s: %s" msg (pp_error e)

let or_fail_with_exn (msg : string) f =
  try f () with e -> Alcotest.failf "%s: %s" msg (Printexc.to_string e)

let _or_fail_with_msg (msg : string) = function
  | Ok v -> v
  | Error e -> Alcotest.failf "%s: %s" msg e

let visible_string =
  Alcotest.testable
    (fun ppf s ->
      let buf = Buffer.create (String.length s * 2) in
      String.iter
        (function
          | '\n' ->
              Buffer.add_string buf
                "↵\n" (* Add symbol AND actual newline for readability *)
          | '\t' -> Buffer.add_string buf "→"
          | ' ' -> Buffer.add_string buf "·"
          | c -> Buffer.add_char buf c)
        s;
      Fmt.string ppf (Buffer.contents buf))
    String.equal

let test_no_readme () =
  let filename =
    (fun () -> Filename.temp_file filename suffix)
    |> or_fail_with_exn "failed to create temp file"
  in

  let todos : Todo.t list =
    [
      {
        urgency = 0;
        msg = "Test TODO";
        marker = Marker.Todo;
        location = { file = filename; line = 1; column = 1 };
      };
    ]
  in
  Readme_io.update_readme ~file_path:filename todos
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme =
    Printf.sprintf
      {|## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|}
      filename
  in

  let updated_readme =
    (fun () -> In_channel.with_open_text filename In_channel.input_all)
    |> or_fail_with_exn ("failed to read updated readme " ^ filename)
  in
  Alcotest.(check visible_string) "same filename" expected_readme updated_readme

let test_empty_readme () =
  let filename, _ =
    (fun () -> Filename.open_temp_file filename suffix)
    |> or_fail_with_exn "failed to create temp file"
  in

  let todos : Todo.t list =
    [
      {
        urgency = 0;
        msg = "Test TODO";
        marker = Marker.Todo;
        location = { file = filename; line = 1; column = 1 };
      };
    ]
  in
  Readme_io.update_readme ~file_path:filename todos
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme =
    Printf.sprintf
      {|## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|}
      filename
  in

  let updated_readme =
    (fun () -> In_channel.with_open_text filename In_channel.input_all)
    |> or_fail_with_exn ("failed to read updated readme " ^ filename)
  in
  Alcotest.(check visible_string) "same filename" expected_readme updated_readme

let test_without_dashboard () =
  let filename, oc =
    (fun () -> Filename.open_temp_file filename suffix)
    |> or_fail_with_exn "failed to create temp file"
  in

  (fun () ->
    Out_channel.output_string oc
      {|# Test README.md

Contains a single paragraph. Tech-debt dashboard should be added below
with a an empty line as separation👇.|};
    Out_channel.close oc)
  |> or_fail_with_exn ("failed to write to test readme " ^ filename);

  let todos : Todo.t list =
    [
      {
        urgency = 0;
        msg = "Test TODO";
        marker = Marker.Todo;
        location = { file = filename; line = 1; column = 1 };
      };
    ]
  in
  Readme_io.update_readme ~file_path:filename todos
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme =
    Printf.sprintf
      {|# Test README.md

Contains a single paragraph. Tech-debt dashboard should be added below
with a an empty line as separation👇.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|}
      filename
  in

  let updated_readme =
    (fun () -> In_channel.with_open_text filename In_channel.input_all)
    |> or_fail_with_exn ("failed to read updated readme " ^ filename)
  in
  Alcotest.(check visible_string) "same filename" expected_readme updated_readme

let test_dashboard_at_top () =
  let filename, oc =
    (fun () -> Filename.open_temp_file filename suffix)
    |> or_fail_with_exn "failed to create temp file"
  in

  (fun () ->
    Out_channel.output_string oc
      {|## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|};
    Out_channel.close oc)
  |> or_fail_with_exn ("failed to write to test readme " ^ filename);

  let todos : Todo.t list =
    [
      {
        urgency = 0;
        msg = "Test TODO";
        marker = Marker.Todo;
        location = { file = filename; line = 1; column = 1 };
      };
    ]
  in
  Readme_io.update_readme ~file_path:filename todos
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme =
    Printf.sprintf
      {|## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|}
      filename
  in

  let updated_readme =
    (fun () -> In_channel.with_open_text filename In_channel.input_all)
    |> or_fail_with_exn ("failed to read updated readme " ^ filename)
  in
  Alcotest.(check visible_string) "same filename" expected_readme updated_readme

let test_dashboard_in_middle () =
  let filename, oc =
    (fun () -> Filename.open_temp_file filename suffix)
    |> or_fail_with_exn "failed to create temp file"
  in

  (fun () ->
    Out_channel.output_string oc
      {|# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|};
    Out_channel.close oc)
  |> or_fail_with_exn ("failed to write to test readme " ^ filename);

  let todos : Todo.t list =
    [
      {
        urgency = 0;
        msg = "Test TODO";
        marker = Marker.Todo;
        location = { file = filename; line = 1; column = 1 };
      };
    ]
  in
  Readme_io.update_readme ~file_path:filename todos
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme =
    Printf.sprintf
      {|# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>

## This should stay

The paragraph AFTER dashbaord should be copied untouched.
|}
      filename
  in

  let updated_readme =
    (fun () -> In_channel.with_open_text filename In_channel.input_all)
    |> or_fail_with_exn ("failed to read updated readme " ^ filename)
  in
  Alcotest.(check visible_string) "same filename" expected_readme updated_readme

let test_dashboard_at_end () =
  let filename, oc =
    (fun () -> Filename.open_temp_file filename suffix)
    |> or_fail_with_exn "failed to create temp file"
  in

  (fun () ->
    Out_channel.output_string oc
      {|# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|};
    Out_channel.close oc)
  |> or_fail_with_exn ("failed to write to test readme " ^ filename);

  let todos : Todo.t list =
    [
      {
        urgency = 0;
        msg = "Test TODO";
        marker = Marker.Todo;
        location = { file = filename; line = 1; column = 1 };
      };
    ]
  in
  Readme_io.update_readme ~file_path:filename todos
  |> or_fail_with "failed to update readme" ~pp_error:Readme_io.error_message;

  let expected_readme =
    Printf.sprintf
      {|# Test README.md

The tech-debt dashbaord BELOW should be replaced.

## Tech Debt Dashboard

> Tech debt is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your debt; resolve it and let it pass.  
> Where the debt has gone, only flow remains.

  - [TODO: Test TODO](%s#L1)

<sub>_— Generated by [MuadʾDebt](https://github.com/cz4rny/muaddebt) 🐫_</sub>
|}
      filename
  in

  let updated_readme =
    (fun () -> In_channel.with_open_text filename In_channel.input_all)
    |> or_fail_with_exn ("failed to read updated readme " ^ filename)
  in
  Alcotest.(check visible_string) "same filename" expected_readme updated_readme

let () =
  Alcotest.run "MuadʾDebt"
    [
      ( "README.md",
        [
          Alcotest.test_case "no_readme" `Quick test_no_readme;
          Alcotest.test_case "empty_readme" `Quick test_empty_readme;
          Alcotest.test_case "no_dashboard" `Quick test_without_dashboard;
          Alcotest.test_case "dashbaord_at_top" `Quick test_dashboard_at_top;
          Alcotest.test_case "dashbaord_in_middle" `Quick
            test_dashboard_in_middle;
          Alcotest.test_case "dashbaord_at_end" `Quick test_dashboard_at_end;
        ] );
    ]
